name: 'create macOS dmg with custom background'
description: 'Create dmg on macOS by actions'
author: 'L-Super, urban233'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'box'
  color: 'green'

# Define your inputs here.
inputs:
  src_dir:
    description: 'Path of the Application Bundle.'
    required: true
    default: 'src_dir'
  dmg_name:
    description: 'Set the name of the output DMG file.'
    required: true
    default: 'dmg_name'
  bg_filepath:
    description: 'Set the filepath to the background image.'
    required: false
    default: 'bg.svg'

runs:
  using: node20
  main: dist/index.js
